### ISSUE TITLE
不知道有人用没，可以在这里留个言呀。是不是整个文档比较好

### ISSUE THREAD

**Issue by xiyaowong** [XiyaoWong/python-iotbot#1]

**Comment by Centauria** [comment]
文档🉑️以🈶️

**Comment by githubdl** [comment]
有个使用文档当然是最好的，我好多指令虽然看得懂一点点，但是总体上还是不怎么会。比如action中写到可以改变图文消息顺序，但是我还是不懂怎么具体操作，另外，如果可以的话，稍微多放几个常见的插件实例，这样用户就可以仿照实例来自己实现一些功能。（不知道这样的请求算不算不要脸，哈哈哈，希望大佬可以整个文档）

**Comment by xiyaowong** [comment]
> 有个使用文档当然是最好的，我好多指令虽然看得懂一点点，但是总体上还是不怎么会。比如action中写到可以改变图文消息顺序，但是我还是不懂怎么具体操作，另外，如果可以的话，稍微多放几个常见的插件实例，这样用户就可以仿照实例来自己实现一些功能。（不知道这样的请求算不算不要脸，哈哈哈，希望大佬可以整个文档）

这个只是一个封装。改图文顺序啥的你要去看iotqq的文档👀

**Comment by StevenJokes** [comment]
所以到底是个啥？QQ助手？
有啥用？
OPQ也看不懂。。
@xiyaowong
