### ISSUE TITLE
插件优先级问题

### ISSUE THREAD

**Issue by ufec** [XiyaoWong/python-iotbot#20]
不知作者有没有考虑一下插件的优先级问题，场景：对于一些指定或含有关键词的信息，我们可以特定处理，对一些平常的消息做另一种处理，在我使用中，我发现好像是在每一个插件里都去处理了这条消息，是否可以采用优先级来处理这个问题呢？按照优先级的顺序加载插件，找到与信息相关的插件后不再引用其他插件，并且这样也能达到对不同信息不同处理的效果

**Comment by xiyaowong** [comment]
优先级有办法实现，但是

> 找到与信息相关的插件后不再引用其他插件

不好实现。
因为只能通过每个插件函数的返回值来判断是否继续运行，这也是原生lua插件的做法。但是这样一条信息排队处理的话时间会很长。而且有的插件功能可能会特意延时，所以又只能限制插件的运行时间，超时就退出，这也是原生lua的做法，但这样导致的限制就很大了
