### ISSUE TITLE
定时器的问题

### ISSUE THREAD

**Issue by ufec** [XiyaoWong/python-iotbot#21]
如图，我创建了定时器
![11111.jpg](https://i.loli.net/2020/09/19/rp1zNmAawgcdlZH.jpg)
但似乎会在任务执行完成后抛出异常

另外我发现好像不支持动态插入定时器，场景：在用户执行某个操作后，需要在未来某个时刻执行某个操作，我尝试动态创建，但貌似不会执行，必须要重新启动主程序，此任务才会重新加载。

另一点，可否考虑在创建实例IOTBOT并启动主程序后，将其注入到插件中，这样一来，启用插件后，实例可以在插件中直接引用，否则创建定时器的话又要重新创建新实例

**Comment by xiyaowong** [comment]
定时任务封装得比较简单。需求多的话就自己写吧。(这些功能我都觉得很勉强了，我自己也没用过😂)

**Comment by xiyaowong** [comment]
可能是我的需求比较简单吧

**Comment by xiyaowong** [comment]
动态添加定时任务可以看看那个第三方库。我也不太记得了

**Comment by ufec** [comment]
OK，感谢大佬，我用apscheduler实现了这个需求，也推荐可以引用这个，scheduler我倒是没怎么用过，之前的需求apscheduler能更好的满足，其实我倒有个建议，将scheduler放在IOTBOT的实例中有点儿不好，就是我说的那个，要重新启动IOTBOT实例的run方法，才能重新加载定时任务

**Comment by xiyaowong** [comment]
> 要重新启动IOTBOT实例的run方法，才能重新加载定时任务

哈哈。我是故意这样做的
