### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by CGH0S7** [XiyaoWong/python-iotbot#22]
![Screenshot_20200926_152531](https://user-images.githubusercontent.com/71083083/94335467-58b62f00-ffcb-11ea-81c5-af8c8ab349ae.jpg)
求解决方案
Python版本：3.8.6rc1

**Comment by xiyaowong** [comment]
这个错误。。。检查下ip和端口吧

**Comment by CGH0S7** [comment]
好了原来我那个端口是tcp，改http后可以启动了
然后再请教一下那个客户端ip怎么填目前我都填了本地ip有问题吗

**Comment by CGH0S7** [comment]
机器人不回复。。

**Comment by xiyaowong** [comment]
截图

**Comment by xiyaowong** [comment]
> 好了原来我那个端口是tcp，改http后可以启动了
> 然后再请教一下那个客户端ip怎么填目前我都填了本地ip有问题吗

没懂你意思。就正常填就行了呀

**Comment by CGH0S7** [comment]
端口冲突导致机能人下线
目前问题已解决感谢帮助
