### ISSUE TITLE
发送群消息问题

### ISSUE THREAD

**Issue by ufec** [XiyaoWong/python-iotbot#23]
![image](https://user-images.githubusercontent.com/34962267/94816893-0348aa80-042f-11eb-9ad0-a6cfb6e13b7b.png)
400是发送文本消息的长度，没超过限制（而且在Linux上好像没限制），演示图在Windows，但无法发送，相同的内容用postman却可以发送，好友消息也可以，群消息就不行

**Comment by xiyaowong** [comment]
消息发送成功没

**Comment by xiyaowong** [comment]
有时候出一些问题很正常

**Comment by Steven52065** [comment]
相同的问题，私聊正常，群消息没有发出，昨天还是可以的，今天突然就不行了

**Comment by xiyaowong** [comment]
应该是bot端的问题。发送群消息一直这样提示？

**Comment by ufec** [comment]
是服务端的问题，弄好了

**Comment by Steven52065** [comment]
@ufec 怎么弄的？麻烦说一下呗
