### ISSUE TITLE
bot.refresh_plugins()无效

### ISSUE THREAD

**Issue by Centauria** [XiyaoWong/python-iotbot#3]
在三四次调用bot.refresh_plugins()之后，插件反而刷新到之前的版本了，再继续调用仍然无果，只能重启

**Comment by xiyaowong** [comment]
我这测试还是没问题。你是用的第一种方式安装的吗？

**Comment by Centauria** [comment]
对，装的最新版

**Comment by xiyaowong** [comment]
🌚🌚

**Comment by Centauria** [comment]
又出现了
在不知道多少次刷新之后
明明磁盘内的文件已经添加了几个函数
然而refresh的时候这些函数会ImportError
![Image](https://user-images.githubusercontent.com/20443216/85224773-35de1280-b3ff-11ea-91fe-a8d6232de680.jpeg)

**Comment by xiyaowong** [comment]
目录有__init__.py文件吗

**Comment by xiyaowong** [comment]
每个目录创建一个__init__.py文件试试。因为插件就是导库，刷新插件就是重载库

**Comment by Centauria** [comment]
所有相关包都是有__init__.py的
难道说bot.refresh_plugins()只能重载`plugins`文件夹里面的代码，而不能重载外部包的代码吗

**Comment by xiyaowong** [comment]
噢噢，那估计就是这样吧

**Comment by Centauria** [comment]
可不可以在下个版本里改进一下QAQ

**Comment by xiyaowong** [comment]
难整

**Comment by XiyaoWong** [comment]
还没找到比较好的办法。要不你试试手动在代码里reload一下。（实在不行就重启吧，emm）
