### ISSUE TITLE
请问如何同时接收多个qq消息

### ISSUE THREAD

**Issue by moyikj** [XiyaoWong/python-iotbot#8]
请问如何同时接收多个qq消息，qq储存在了list里面，试了好多方法，都无法获取多个qq的信息，求解

**Comment by xiyaowong** [comment]
多个QQ是啥意思。你有多Q权限吗？不同QQ的消息中CurrentQQ字段是不同的

**Comment by moyikj** [comment]
你好，程序开发完成后将会有多q的权限

比如现在是这样的，如果我想要将一个列表bots = [111,222]这些qq，批量接收消息的话
我想使用这样的方式
for i in bots:
&nbsp; &nbsp; bot[i] = ........


但是在这里遇到了问题，也就是说接收消息时只能写很多重复的函数？
@bot.on_group_msg

如果这么写会报错↓
@bot[1].on_group_msg





请问有没有哪种方式可以接收所有消息，然后让我自己用
ctx.get('CurrentQQ')
进行qq的判断
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiyaowong/python--iotbot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 上午6:15
收件人:&nbsp;"xiyaowong/python--iotbot"<python--iotbot@noreply.github.com&gt;;
抄送:&nbsp;"moyi_tech"<1454913085@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiyaowong/python--iotbot] 请问如何同时接收多个qq消息 (#8)





 
多个QQ是啥意思。你有多Q权限吗？不同QQ的消息中CurrentQQ字段是不同的

**Comment by xiyaowong** [comment]
不能这样写，不管你是挂了几个qq，客户端只有一个

**Comment by moyikj** [comment]
哦哦，那我想要同时接收多个qq消息要怎么做呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiyaowong/python--iotbot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 中午12:47
收件人:&nbsp;"xiyaowong/python--iotbot"<python--iotbot@noreply.github.com&gt;;
抄送:&nbsp;"moyi_tech"<1454913085@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiyaowong/python--iotbot] 请问如何同时接收多个qq消息 (#8)





 
不能这样写，不管你是挂了几个qq，客户端只有一个

**Comment by xiyaowong** [comment]
会接收到的。只是传过来的数据CurrentQQ字段不同

**Comment by moyikj** [comment]
bot&nbsp;=&nbsp;IOTBOT(181454755,&nbsp;port=1008,&nbsp;beat_delay=60,&nbsp;host='http://192.168.123.240')



但是，我将qq参数修改后，智能接收到指定qq的消息，并没有收到所有消息
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiyaowong/python--iotbot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 中午12:54
收件人:&nbsp;"xiyaowong/python--iotbot"<python--iotbot@noreply.github.com&gt;;
抄送:&nbsp;"moyi_tech"<1454913085@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiyaowong/python--iotbot] 请问如何同时接收多个qq消息 (#8)





 
会接收到的。只是传过来的数据CurrentQQ字段不同

**Comment by xiyaowong** [comment]
另一个QQ登录了吗？没多Q权限是登不上的。如果有多Q，第一个参数就传入QQ号列表。还有你在github回复吧。邮箱回复太乱了

**Comment by moyikj** [comment]
bot = IOTBOT([1814547755, 207887202], port=1008, beat_delay=60, host='http://192.168.123.240')

你好，有多Q权限我是这么写的，但是一个qq的消息都收不到

**Comment by xiyaowong** [comment]
发一下机器人框架端的log

**Comment by moyikj** [comment]
2020/08/07 20:02:19.118 [A]  GetWebConn [1814547755, 207887202]

**Comment by xiyaowong** [comment]
是从github在先安装的吗

**Comment by xiyaowong** [comment]
通过pip install 安装的是很久之前的版本

**Comment by moyikj** [comment]
我之前安装的，可能是版本问题，我更新下吧，谢谢了
